
global:
  smtp_smarthost: 'localhost:1025'
  smtp_from: 'alertmanager@example.org'
  smtp_require_tls: false
 
route:
  receiver: 'hoge-ml'
  group_by: ['alertname', 'cluster']
  group_wait: 3s
  group_interval: 5s
  repeat_interval: 1m

receivers:
- name: 'hoge-ml'
  email_configs:
  - to: 'hoge@example.com'
    send_resolved: true
