
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
      monitor: 'codelab-monitor'

rule_files:
  - ../../prometheus-rules/general.rules
  - ../../prometheus-rules/cpu-usage.rules
  - ../../prometheus-rules/load-average.rules
  - ../../prometheus-rules/low-disk-space.rules
  - ../../prometheus-rules/mem-usage.rules
  - ../../prometheus-rules/mysqld.rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'mysql'
    static_configs:
      - targets:
          - 'localhost:9104'

  - job_name: 'node'
    static_configs:
      - targets:
          - 'localhost:9100'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['localhost:9093']
